### ISSUE TITLE
오류가 있어 질문드립니다.

### ISSUE THREAD

**Issue by wingtgniw** [YongWookHa/Open-OCR-Engine#1]
안녕하세요.

이미지 AI 응용프로그램을 개발중인 김태원이라고 합니다.

몇 가지 질문이 있어 메세지 남깁니다.

질문 1:

![OCR_error (2)](https://user-images.githubusercontent.com/53434687/199188582-3c1bde96-8dcb-4327-8598-ea3a5255d238.PNG)

위의 이미지처럼 데이터의 인자가 맞지 않는 오류가 있습니다.

pytorch 버전 문제로 보이는데 어떤 버전 사용하셨을까요?

질문 2:
영문 데이터와 한글 데이터를 혼합해서 학습 시키려면 어떤 방법으로 해야 할까요?

**Comment by YongWookHa** [comment]
늦게나마 질문에 답변드립니다.
본 레포지토리는 더이상 유지보수되지 않고 있는 점, 양해바랍니다.

1. pytorch 및 pytorch lightning 버전의 문제인 것 같습니다. torch 1.12.1 + cu11.3 을 쓰고 있습니다.
2. 한글, 영문 혼용 모델 개발을 원하시면 recognizer (문자 인식기) 앞단에 language classifier를 붙이는 것이 효과적입니다. 한글과 영문을 통합한 모델은 vocab등의 문제로 인식 성능이 현저히 떨어지는 것으로 알고 있습니다.

**Comment by wingtgniw** [comment]
답변 감사합니다.

다른 질문이긴 한데

외국에 나가신걸로 아는데 혹시 실례가 안된다면

현재 소속되어 있는 회사가 있으신지 알 수 있을까요?

저희 회사에서 내부 프로젝트로 이미지 AI 응용 프로그램을 개발중인데

혹시 관심 있으시면 같이 일해보고 싶어서 다시 메일 보냅니다.

김태원 드림

2022년 11월 7일 (월) 오후 10:39, Ha YongWook ***@***.***>님이 작성:

**Comment by YongWookHa** [comment]
안녕하세요. 하용욱입니다.

관심 감사합니다.

저는 현재 강남 소재의 AI 특허 분석 스타트업에서 리드 개발자로 소속되어 일하고 있습니다.
아시는대로 현재는 외국에 거주중이라 원격 근무로 일하고 있지만, 12월 중에 귀국할 예정입니다.
곧 처우 재협상 시즌을 앞두고 있어 xyz에서 제안하시는 조건에 대해서도 고려해보고 싶습니다.

감사합니다.

2022년 11월 7일 (월) 오후 6:38, wingtgniw ***@***.***>님이 작성:

**Comment by wingtgniw** [comment]
긍정적인 답변 감사합니다.

제가 윗선과 계약조건에 대해 이야기를 진행 해보려고 하는데

이력서를 받을 수 있을까요?

김태원 드림

2022년 11월 8일 (화) 오전 11:50, Ha YongWook ***@***.***>님이 작성:
